// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
  class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9p46BmRW9QrN5UNTg2r7mGQmF03NJxo',
    appId: '1:896111971029:web:938e0bf0f10d638c83f05c',
    messagingSenderId: '896111971029',
    projectId: 'status-saver-fede0',
    authDomain: 'status-saver-fede0.firebaseapp.com',
    storageBucket: 'status-saver-fede0.appspot.com',
    measurementId: 'G-JXYSSS39H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9HNF9Zld4JfXtTjoKoF_DQSbpyosyKVs',
    appId: '1:896111971029:android:7f78c3ce61f2b1a483f05c',
    messagingSenderId: '896111971029',
    projectId: 'status-saver-fede0',
    storageBucket: 'status-saver-fede0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWHJ5Re2CV_jwDK2qy9fT2ufiPIuBkehQ',
    appId: '1:896111971029:ios:741ba37102fb22e683f05c',
    messagingSenderId: '896111971029',
    projectId: 'status-saver-fede0',
    storageBucket: 'status-saver-fede0.appspot.com',
    iosClientId: '896111971029-vtii3j6itkmlmjdmk28c1s9e17f0v3ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppSaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWHJ5Re2CV_jwDK2qy9fT2ufiPIuBkehQ',
    appId: '1:896111971029:ios:741ba37102fb22e683f05c',
    messagingSenderId: '896111971029',
    projectId: 'status-saver-fede0',
    storageBucket: 'status-saver-fede0.appspot.com',
    iosClientId: '896111971029-vtii3j6itkmlmjdmk28c1s9e17f0v3ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppSaver',
  );
}
